--!strict
export type icons = {
	[Enum.KeyCode | Enum.UserInputType] : string
}

export type Device = {
	Keyboard : icons,
	Gamepad : icons
}

return {
	Keyboard = {
		[Enum.KeyCode.A] = 'rbxassetid://122197956331720',
		[Enum.KeyCode.B] = 'rbxassetid://138122784714462',
		[Enum.KeyCode.C] = 'rbxassetid://112269350003032',
		[Enum.KeyCode.D] = 'rbxassetid://138770271134688',
		[Enum.KeyCode.E] = 'rbxassetid://94028859599068',
		[Enum.KeyCode.F] = 'rbxassetid://131702503730277',
		[Enum.KeyCode.G] = 'rbxassetid://121609794178479',
		[Enum.KeyCode.H] = 'rbxassetid://77776651140874',
		[Enum.KeyCode.I] = 'rbxassetid://140497731786838',
		[Enum.KeyCode.J] = 'rbxassetid://117203215116082',
		[Enum.KeyCode.K] = 'rbxassetid://71330849501285',
		[Enum.KeyCode.L] = 'rbxassetid://123421292108228',
		[Enum.KeyCode.M] = 'rbxassetid://104107625532068',
		[Enum.KeyCode.N] = 'rbxassetid://84083241201481',
		[Enum.KeyCode.O] = 'rbxassetid://73020316958982',
		[Enum.KeyCode.P] = 'rbxassetid://99121299386961',
		[Enum.KeyCode.Q] = 'rbxassetid://91464896711890',
		[Enum.KeyCode.R] = 'rbxassetid://94018279031513',
		[Enum.KeyCode.S] = 'rbxassetid://121874037539067',
		[Enum.KeyCode.T] = 'rbxassetid://129958111247107',
		[Enum.KeyCode.U] = 'rbxassetid://88457305542489',
		[Enum.KeyCode.V] = 'rbxassetid://76969178950490',
		[Enum.KeyCode.W] = 'rbxassetid://75632892950550',
		[Enum.KeyCode.X] = 'rbxassetid://132550853335011',
		[Enum.KeyCode.Y] = 'rbxassetid://117099617847608',
		[Enum.KeyCode.Z] = 'rbxassetid://114788234784266',

		[Enum.KeyCode.One] = 'rbxassetid://87214341748899',
		[Enum.KeyCode.Two] = 'rbxassetid://114645597381949',
		[Enum.KeyCode.Three] = 'rbxassetid://85894592416474',
		[Enum.KeyCode.Four] = 'rbxassetid://71979637891316',
		[Enum.KeyCode.Five] = 'rbxassetid://114630841984771',
		[Enum.KeyCode.Six] = 'rbxassetid://80505193897332',
		[Enum.KeyCode.Seven] = 'rbxassetid://128120858225085',
		[Enum.KeyCode.Eight] = 'rbxassetid://95059347879780',
		[Enum.KeyCode.Nine] = 'rbxassetid://117262205732075',
		[Enum.KeyCode.Zero] = 'rbxassetid://140309253472983',

		[Enum.KeyCode.LeftControl] = 'rbxassetid://125162600457608',
		[Enum.KeyCode.RightControl] = 'rbxassetid://125162600457608',
		[Enum.KeyCode.LeftShift] = 'rbxassetid://109762030406601',
		[Enum.KeyCode.RightShift] = 'rbxassetid://109762030406601',
		[Enum.KeyCode.LeftAlt] = 'rbxassetid://77209258271852',
		[Enum.KeyCode.RightAlt] = 'rbxassetid://77209258271852',
		[Enum.KeyCode.Tab] = 'rbxassetid://88381950166432',
		[Enum.KeyCode.CapsLock] = 'rbxassetid://111108954866164',
		[Enum.KeyCode.Backspace] = 'rbxassetid://71470915905257',
		[Enum.KeyCode.KeypadEnter] = 'rbxassetid://82150526477450',
		[Enum.KeyCode.Space] = 'rbxassetid://76685717738799',
		[Enum.KeyCode.Tilde] = 'rbxassetid://117971562451317',

		[Enum.KeyCode.Insert] = 'rbxassetid://81782876674611',
		[Enum.KeyCode.Home] = 'rbxassetid://116068356061022',
		[Enum.KeyCode.Delete] = 'rbxassetid://126463489514045',
		[Enum.KeyCode.End] = 'rbxassetid://128593440255971',
		[Enum.KeyCode.PageUp] = 'rbxassetid://123418308626632',
		[Enum.KeyCode.PageDown] = 'rbxassetid://132249550976909',
		[Enum.KeyCode.Minus] = 'rbxassetid://73640656237008',
		[Enum.KeyCode.Plus] = 'rbxassetid://80670030842750',
		[Enum.KeyCode.BackSlash] = 'rbxassetid://109108231279007',
		[Enum.KeyCode.Question] = 'rbxassetid://75913352156542',
		[Enum.KeyCode.LeftBracket] = 'rbxassetid://115165261997657',
		[Enum.KeyCode.RightBracket] = 'rbxassetid://140704483217689',
		[Enum.KeyCode.Semicolon] = 'rbxassetid://100731468717339',
		[Enum.KeyCode.GreaterThan] = 'rbxassetid://94198052589693',
		[Enum.KeyCode.LessThan] = 'rbxassetid://122332713899546',
		[Enum.KeyCode.Escape] = 'rbxassetid://85446410190975',

		[Enum.KeyCode.Up] = 'rbxassetid://108869827999882',
		[Enum.KeyCode.Right] = 'rbxassetid://116165045478014',
		[Enum.KeyCode.Down] = 'rbxassetid://112528724223853',
		[Enum.KeyCode.Left] = 'rbxassetid://87090699654252',

		[Enum.UserInputType.MouseButton1] = 'rbxassetid://102349916400213',
		[Enum.UserInputType.MouseButton2] = 'rbxassetid://132175446041871',
		[Enum.UserInputType.MouseButton3] = 'rbxassetid://89996528989274',
		[Enum.UserInputType.MouseWheel] = 'rbxassetid://75215218440075',
	},
	Gamepad = {
		[Enum.KeyCode.ButtonL1] = 'rbxassetid://86424254919520',
		[Enum.KeyCode.ButtonL2] = 'rbxassetid://82652826840027',
		[Enum.KeyCode.ButtonL3] = 'rbxassetid://99526545977048',
		[Enum.KeyCode.ButtonR1] = 'rbxassetid://123971997746177',
		[Enum.KeyCode.ButtonR2] = 'rbxassetid://104438871805053',
		[Enum.KeyCode.ButtonR3] = 'rbxassetid://78640754630861',

		[Enum.KeyCode.ButtonA] = 'rbxassetid://85014498129241',
		[Enum.KeyCode.ButtonB] = 'rbxassetid://75083838842052',
		[Enum.KeyCode.ButtonX] = 'rbxassetid://138203273595821',
		[Enum.KeyCode.ButtonY] = 'rbxassetid://86066508051187',

		[Enum.KeyCode.DPadUp] = 'rbxassetid://107488279351292',
		[Enum.KeyCode.DPadDown] = 'rbxassetid://93154814600549',
		[Enum.KeyCode.DPadLeft] = 'rbxassetid://124146897990290',
		[Enum.KeyCode.DPadRight] = 'rbxassetid://117194004743792',

		[Enum.KeyCode.Menu] = 'rbxassetid://83463538173924'
	},
} :: Device